name: Download Red Hat Documentation

on:
  workflow_dispatch:
    inputs:
      product_name:
        description: 'Product name (e.g., openshift_container_platform)'
        required: true
      product_version:
        description: 'Product version (e.g., 4.18)'
        required: true
      base_url:
        description: 'Base documentation URL'
        required: false
        default: 'https://docs.redhat.com/en/documentation/'
      headless:
        description: 'Run in headless mode'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
  schedule:
    # Run monthly on the 1st at 2:00 AM UTC
    - cron: '0 2 1 * *'

jobs:
  download-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Set default parameters (for scheduled runs)
      if: github.event_name == 'schedule'
      run: |
        echo "PRODUCT_NAME=openshift_container_platform" >> $GITHUB_ENV
        echo "PRODUCT_VERSION=4.14" >> $GITHUB_ENV
        echo "BASE_URL=https://docs.redhat.com/en/documentation/" >> $GITHUB_ENV
        echo "HEADLESS=true" >> $GITHUB_ENV
        
    - name: Set manual parameters (for workflow_dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "PRODUCT_NAME=${{ github.event.inputs.product_name }}" >> $GITHUB_ENV
        echo "PRODUCT_VERSION=${{ github.event.inputs.product_version }}" >> $GITHUB_ENV
        echo "BASE_URL=${{ github.event.inputs.base_url }}" >> $GITHUB_ENV
        echo "HEADLESS=${{ github.event.inputs.headless }}" >> $GITHUB_ENV
        
    - name: Run documentation downloader
      run: node docs-downloader.js --product-name "$PRODUCT_NAME" --product-version "$PRODUCT_VERSION" --base-url "$BASE_URL" --headless "$HEADLESS"
      
    - name: Upload downloaded PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: redhat-docs-${{ env.PRODUCT_NAME }}-${{ env.PRODUCT_VERSION }}
        path: downloads/
        retention-days: 30
        
    - name: Upload download results json
      uses: actions/upload-artifact@v4
      with:
        name: download-results-${{ env.PRODUCT_NAME }}-${{ env.PRODUCT_VERSION }}
        path: "*-download-results.json"
        retention-days: 30
